### ISSUE TITLE
New mysql authentication script

### ISSUE THREAD

**Issue by cdauth** [processone/docs.ejabberd.im#10]
As a follow-up to #9, I have extended the python mysql external authentication script and added the following features to it:

* Use custom password hash algorithm
* Define custom SQL queries to make custom database layouts possible
* Add support for changing password, registering, and unregistering

I have put the script into the repository [rankenstein/ejabberd-auth-mysql](https://github.com/rankenstein/ejabberd-auth-mysql). It would be nice if it could be linked among the [external auth scripts](https://www.ejabberd.im/extauth).

**Comment by badlop** [comment]
Ok, I've updated the page: https://www.ejabberd.im/ejabberd-auth-mysql
