### ISSUE TITLE
Admin->Configuration-Database/LDAP - ldap_uidattr & ldap_uidattr_format 

### ISSUE THREAD

**Issue by ingoj** [processone/docs.ejabberd.im#100]
ldap_uidattr & ldap_uidattr_format are mentioned on https://docs.ejabberd.im/admin/configuration/database-ldap/, but giving 404/non-existent. Were those options removed or is the documentation for this missing?

**Comment by prefiks** [comment]
Those options were replaced with `ldap_uids`, it covers same information as both of those options did. I will try remove refs to those from documentation.
