### ISSUE TITLE
Search should specify which ejabberd version the results are from

### ISSUE THREAD

**Issue by licaon-kter** [processone/docs.ejabberd.im#107]
Eg. search for "sm_cache_size" see 10 results, some from /archive/version some from /admin/

Yes, browser status bar might show the URL and one can find out, but in mobile browsers that's not a feature.

**Comment by badlop** [comment]
Just as an experiment, I've added the version number to the archived "Modules Options" pages titles in https://github.com/processone/docs.ejabberd.im/commit/28805d462b1df12f9a1b12c9c0519829558e427d

I hope that will provide information in the Search results... as soon as the search engine uses the updated page- I don't know when is that updated.

**Comment by badlop** [comment]
Fixed with this PR that avoids crawling /archive in Algolia: https://github.com/algolia/docsearch-configs/pull/4421
