### ISSUE TITLE
Search results - sort by ejabberd version, newer on top

### ISSUE THREAD

**Issue by licaon-kter** [processone/docs.ejabberd.im#108]
Eg. search for "sm_cache_size" see 10 results, the order is:

20.07
20.04
20.12
21.01
21.04

..which looks rather random

**Comment by badlop** [comment]
Looking at the Algolia documentation, it would be possible somehow to group those results, and sort them... But a more simple solution was simply to not crawl the /archive path: https://github.com/processone/docs.ejabberd.im/issues/107
