### ISSUE TITLE
XEP-0156 _xmppconnect is vulnerable to MITM

### ISSUE THREAD

**Issue by moparisthebest** [processone/docs.ejabberd.im#113]
Context: https://mail.jabber.org/pipermail/standards/2022-February/038759.html

Vulnerable code: https://github.com/processone/docs.ejabberd.im/blob/5a6125fe6ff66e714c05450c16ef7a9ed05708f4/content/admin/configuration/listen.md?plain=1#L438

**Comment by badlop** [comment]
Thanks for reporting! As immediate action, I've removed the mention to DNS TXT.

It would be nice to explain in that section how to setup host-meta in ejabberd.

**Comment by badlop** [comment]
> It would be nice to explain in that section how to setup host-meta in ejabberd.

I've added mod_host_meta, which provides host-meta files when enabled and configured
https://github.com/processone/ejabberd/commit/8065ec831eb5e7681d749c2e3265da68e10b4d55

This should be mentioned in the documentation when the next ejabberd version is released.
