### ISSUE TITLE
src/mod_mam.erl:224: variable 'Opt' is unbound

### ISSUE THREAD

**Issue by frey1esm** [processone/docs.ejabberd.im#16]
When compiling, I got this error:

```
src/mod_mam.erl:224: variable 'Opt' is unbound
ERROR: compile failed while processing /Users/david/Documents/HSWEB/mobile/apps/HiLois/ejabberd/ejabberd: rebar_abort
make: *** [deps/.built] Error 1
```

**Comment by zinid** [comment]
You have opened the issue in the wrong repo :)
This is fixed however in this commit: https://github.com/processone/ejabberd/commit/f6e960d326fd1fe863ac812ed6ba3dfb7651763e
