### ISSUE TITLE
unknown option 'c2s_auth_block_lifetime' for module 'mod_fail2ban'

### ISSUE THREAD

**Issue by DmitrySandalov** [processone/docs.ejabberd.im#26]
`mod_fail2ban` fails with the following config:

    mod_fail2ban:
      c2s_auth_block_lifetime: 7200
      c2s_max_auth_failures: 50

Error with ejabberd 17.04:

    [error] unknown option 'c2s_auth_block_lifetime' for module 'mod_fail2ban' will be likely ignored, available options are: 'access', 'c2s_auth_ban_lifetime', 'c2s_max_auth_failures'

**Comment by badlop** [comment]
Thanks for reporting!

I've applied your fix to the original documentation code, and will be applied here, and published, in the next release.
