### ISSUE TITLE
New caching parameters not yet described

### ISSUE THREAD

**Issue by MarcelWaldvogel** [processone/docs.ejabberd.im#29]
https://docs.ejabberd.im/admin/configuration/#external-script still describes the old caching behavior, which has changed with 17.06. I was unable to find good documentation of it anywhere else.

This is especially important to `extauth`, as the current cache (which is now on by default) results in false login refusals, if multiple passwords are valid, when using 'app passwords' or similar. They are hard to track down, believe me.

**Comment by badlop** [comment]
@zinid, do you consider the PR is ready to commit?

**Comment by zinid** [comment]
@badlop in the commit, `extauth_cache` is kept untouched, which is not strictly speaking correct, because the parameter doesn't take effect anymore, IIRC.

**Comment by MarcelWaldvogel** [comment]
A lot of installations/distros come with an earlier version of ejabberd. They still use this for reference. Therefore, I decided to keep it untouched. Do you have another versioning mechanism which these users could rely on?

**Comment by badlop** [comment]
Ok, I've committed your explanation, and removed the extauth_cache one.

> Do you have another versioning mechanism which these users could rely on?

From what I know, no.
