### ISSUE TITLE
deprecated "steam_management" option in docs

### ISSUE THREAD

**Issue by nekoswag** [processone/docs.ejabberd.im#32]
When having "stream_management" under the listener module, ejabberd will complain in debug mode that this option is deprecated.
It is in fact, since 17.03, but the documentation about it is not yet updated.

https://blog.process-one.net/ejabberd-17-03/
https://docs.ejabberd.im/admin/configuration/#listening-module

It should be in the docs that XEP-0198 is now its own module and should be enabled with
mod_stream_mgmt

**Comment by badlop** [comment]
Ok, in the original doc git, I've documented the module, and will be automerged in this one and online in the next release. So this ticket can be closed.
