### ISSUE TITLE
mod_http_bind mentioned in mod_bosh config sample

### ISSUE THREAD

**Issue by tbeitter** [processone/docs.ejabberd.im#34]
The documentation of options for for mod_bosh tells to configure mod_http_bin

> modules:
>   ...
>   mod_http_bind:
>     max_inactivity: 50
>   ...

See https://docs.ejabberd.im/admin/configuration/#mod-bosh

**Comment by cromain** [comment]
oups.... i'll check and fix. Likely migration mistake. Thanks for reporting !

**Comment by cromain** [comment]
this is fixed upstream
