### ISSUE TITLE
Anchors dont' work without page reload

### ISSUE THREAD

**Issue by gardenia** [processone/docs.ejabberd.im#38]
Lets say I go here:

https://docs.ejabberd.im/admin/configuration/

Click on a sub-topic such as "Basic Configuration"

the internal anchors dont' work (on Chrome anyhow).

I found that if I right-click the link and open in new tab it will work.

The page reload behavior suggests that some javascript or CSS is responsible for it workg at page reload time.   but it is a pretty frustrating user experience that internal anchors dont' work.

**Comment by gardenia** [comment]
PS - I was going to poke around with trying to fix this myself I can't seem to find any instructions regarding how the docs are built (or rendered).  I'd be happy to look into it if you could provide more details on that.  I did read that it uses kramdown but it would be good to get more specifics than that.

**Comment by badlop** [comment]
I have the same problem since some moths ago. I thought it was somethgnin my browser...

@f055 any idea?

**Comment by f055** [comment]
Let me know your browser versions, I will try to replicate. I tested on Chrome Version 56.0.2924.87 (64-bit) and all works fine.

**Comment by gardenia** [comment]
Here is my Chrome version (running on Ubuntu 16.04):

Version 63.0.3239.108 (Official Build) (64-bit)

thx

**Comment by badlop** [comment]
It's probably fixed :) It works for me now, with the same version than gardenia, and it failed for me previously.

**Comment by gardenia** [comment]
verified working for me also.  thx.

**Comment by f055** [comment]
Great, thanks for the info 👍
