### ISSUE TITLE
Unknown option 'mam' of module 'mod_muc' since ejabberd 18.06

### ISSUE THREAD

**Issue by alexara** [processone/docs.ejabberd.im#46]
`https://docs.ejabberd.im/admin/configuration/#mod-muc`

It should be stated that the option `mam` has been depcrecated since version 18.06:

`11:19:19.241 [error] Unknown option 'mam' of module 'mod_muc', available options are: user_presence_shaper, user_message_shaper, room_shaper, access_register, default_room_options, max_users, max_user_conferences, max_rooms_discoitems, max_roo
m_desc, hosts, access, regexp_room_id, max_users_admin_threshold, max_room_id, host, access_persistent, queue_type, max_users_presence, max_room_name, name, history_size, ram_db_type, db_type, access_create, min_presence_interval, min_message_
interval, access_admin
`

**Comment by zinid** [comment]
There was never an option `mam` in `mod_muc`. It's a sub-option of option `default_room_config` of `mod_muc`.

**Comment by alexara** [comment]
> There was never an option mam in mod_muc. It's a sub-option of option default_room_options of mod_muc.

Shame on me! My bad!
