### ISSUE TITLE
Have a perfect documentation

### ISSUE THREAD

**Issue by Neustradamus** [processone/docs.ejabberd.im#56]
- TLS (no_..., ciphers, s2s_use_starttls: optional -> required?)
- certfile and s2s_certfile old part -> certificates part?
- mod_vcard_ldap part -> mod_vcard with "db_type: ldap"?

Linked to:
- https://github.com/processone/ejabberd/issues/2665
- https://github.com/processone/ejabberd/issues/2707

**Comment by badlop** [comment]
> mod_vcard_ldap part -> mod_vcard with "db_type: ldap"?

Yes, this has been fixed recently.

> certfile and s2s_certfile old part -> certificates part?

Do you remember when or where was this change applied in the code? I can't find it.

**Comment by Neustradamus** [comment]
https://github.com/processone/ejabberd/commit/35b7203e01aefbdfe4ea7804ebe20a8667466628

**Comment by badlop** [comment]
Great! I've documented the certfiles option, and removed certfile and older options when they were no longer supported. Notice certfile is still used by ejabberd_sip and ejabberd_stun.

**Comment by Neustradamus** [comment]
@badlop, it is possible to update for ejabberd_sip and ejabberd_stun?

**Comment by badlop** [comment]
If it were possible, it would have been done when the other modules were updated.

**Comment by cromain** [comment]
I merged latest changes.
@badlop i let you handle the two undocumented new options.

**Comment by badlop** [comment]
There were several more c2s_ options missing documentation. I've copied the descriptions from the equivalent s2s_ options, and committed it.
