### ISSUE TITLE
Provide documentation for older ejabberd releases

### ISSUE THREAD

**Issue by badlop** [processone/docs.ejabberd.im#79]
ejabberd documentation's source code is available in this git repository. Then, admins have a human-readable online version at https://docs.ejabberd.im 

But how can admins of old releases access old documentation versions? The admin of ejabberd 18.01 should not check the up-to-date online documentation, as there were changes in the configuration syntax.

Back when documentation was in LateX, the guide was included as pdf in each release, so each admin checked the exact documentation for his version.

Possible solutions:
- Do nothing: only the admins of current version can access correct documentation; everyone else will fill tickets and [forum posts](https://stackoverflow.com/questions/58802951/in-ejabberd-mod-http-upload-returns-ignoring-listen-option-request-handlers) asking why his not-up-to-date ejabberd complains about a configuration copied from online documentation
- Do nothing, and redirect admins of old versions to https://web.archive.org/
- Provide a docs/ dir with each release, so it's included in the packages. Apparently this is what Erlang/OTP does
- Perform a backup of docs site for each release, and host them in a "Docs archive" section. Either in html, or pdf

**Comment by licaon-kter** [comment]
Why not Tag the docs on each release?

**Comment by f055** [comment]
I think the simplest method will be, with each new release, to create a new read-only branch from master as a snapshot of the docs at that point in time. What do you think? The docs site won't be impacted as it's synced from master, but also gives an easy way to switch the docs site to a different version if needed.

**Comment by badlop** [comment]
Right, in this sense, I'm experimenting with two complementary solutions:
* tag the docs git repository in each new release
* _Archive_ section in the docs site that keeps a backup of sections that usually change: https://docs.ejabberd.im/archive/
