### ISSUE TITLE
Github repo not updated

### ISSUE THREAD

**Issue by licaon-kter** [processone/docs.ejabberd.im#84]
https://github.com/processone/docs.ejabberd.im/blob/master/content/admin/configuration.md#captcha (_host)

vs

https://docs.ejabberd.im/admin/configuration/#captcha (_url) up to date as: https://github.com/processone/ejabberd/commit/d85cf7780c76e20b6d7290aa49050161bc352496

**Comment by badlop** [comment]
Repository updated, now let's see how to update the online site.

**Comment by licaon-kter** [comment]
Thanks

**Comment by mremond** [comment]
@badlop The online site is updated on commit on the private doc repo.
