### ISSUE TITLE
No XEP-0384: OMEMO Encryption indications in documentation

### ISSUE THREAD

**Issue by Neustradamus** [processone/docs.ejabberd.im#87]
Can you add indications for XEP-0384: OMEMO Encryption in documentation?
- https://xmpp.org/extensions/xep-0384.html

**Comment by licaon-kter** [comment]
What exactly? This is not a server function.

Yes it's compatible but...

**Comment by Neustradamus** [comment]
@licaon-kter: Nothing about OMEMO informations: "force_node_config" etc.

**Comment by licaon-kter** [comment]
Why would they? Anyway, better PR the docs instead.

**Comment by badlop** [comment]
XEP-0384 does not require specific server implementation, so servers don't advertice its support explicitly, see the pages of other XMPP servers like Prosody, Tigase or Openfire.

**Comment by Neustradamus** [comment]
ejabberd blocks...
>     force_node_config:	    force_node_config:
>       ## Change from "whitelist" to "open" to enable OMEMO support	
>       ## See https://github.com/processone/ejabberd/issues/2425	
>       "eu.siacs.conversations.axolotl.*":	
>         access_model: whitelist

**Comment by licaon-kter** [comment]
In what file is that currently?

**Comment by Neustradamus** [comment]
In distribution, ejabberd has not up-to-date file, and people do not understand.
Please specify in the docs.ejabberd.im that in ejabberd XX.XX and XX.XX the ejabberd.yml was blocked OMEMO by default...
