### ISSUE TITLE
SQL injection vulnerability in Python MySQL auth script

### ISSUE THREAD

**Issue by cdauth** [processone/docs.ejabberd.im#9]
I am new to ejabberd and I don’t know it this is the right place to report this issue.

It seems to me that the script linked [here](https://www.ejabberd.im/check_mysql_python) has an SQL injection vulnerability in line 75.The parameter `in_user` comes from the client and thus needs to be escaped:

```python
dbcur.execute("SELECT %s,%s FROM %s WHERE %s = %%s"%(db_username_field, db_password_field, db_table, db_username_field), (in_user))
```

**Comment by badlop** [comment]
Thanks for reporting. Fixed the script in that page.

**Comment by cdauth** [comment]
Thanks for fixing. For future reference, is this the right place to report issues like that?

**Comment by badlop** [comment]
Yes, it seems a good place for documentation stuff. For code stuff there's the ejabberd page https://github.com/processone/ejabberd/
