### ISSUE TITLE
Some simple documentation clarifications

### ISSUE THREAD

**Issue by htgoebel** [processone/docs.ejabberd.im#94]
Please clarify in the documentation:
* Global options: Will `c2s_{protocoll_options,ciphers,dhfile}` provided defaults to the "listen" modules? Same for `s2s_*`
* Listen-options: Are ciphers, dhfile, protocoll_options defaulting to the global `c2s` resp. `s2s` options?
* What module/function is using `s2s_starttls`? Is this for outgoing messages, and thus needs to be defined here (as this is not a listening module)

* Hat is the meaning of `hosts` in mod_http_upload, mod_muc, mod_mix and others?
  What is this used for? Can one use `@HOST@` (without any prefix)?
  What is the benefit of listing more than one hosts / JIDs?

* mod_pres_counter: `interval`: Unit of value us not documented.

* Meaning of mod_register: `access_from` is unclear: Description lets assume this is for controlling registration of new accounts from s2s or existing c2s sessions. But This is not stated.

* `mod_stun` has an option to enable TLS, but what ciphers, dhfile, and protocoll_options are used?

Many thanks in advance for improving the documentation :-)

**Comment by badlop** [comment]
Did you investigate the answers to your questions?

Many thanks in advance for sending a PR to improve the documentation!

**Comment by htgoebel** [comment]
@badlop I dod not receive any answer to the questions.

**Comment by badlop** [comment]
> Global options: Will c2s_{protocoll_options,ciphers,dhfile} provided defaults to the "listen" modules? Same for s2s_*

The options certfile, ciphers, protocol_options, dhfile, cafile, tls_compression in c2s listener are only used if the corresponding top-level c2s_* option is undefined.

Same happens for incoming S2S connections: the top-level s2s_* options are prefered. When undefined, ejabberd uses the options defined in ejabberd_s2s_in listen module.

For outgoing S2S connections, the top-level s2s_* options are used.


> Listen-options: Are ciphers, dhfile, protocoll_options defaulting to the global c2s resp. s2s options?

The options in ejabberd_service and ejabberd_http listener modules are not affected by any other c2s_* or s2s_* top-level option you may set.


> What module/function is using s2s_starttls? Is this for outgoing messages, and thus needs to be defined here (as this is not a listening module)

Where did you read that option? It isn't mentioned anywhere in ejabberd 21.04 source code.


> Hat is the meaning of hosts in mod_http_upload, mod_muc, mod_mix and others?

This option defines the Jabber IDs of the service.


> What is this used for?

To define what JID the service with listen in.


> Can one use @HOST@ (without any prefix)?

No.


> What is the benefit of listing more than one hosts / JIDs?

The service will be available in several JIDs.


> mod_pres_counter: interval: Unit of value us not documented.

This and other timeout() options do not enforce a specific unit, the admin defines it along with the integer:
```yaml
interval: 30 secs
interval: 1 minute
interval: 10000000 milliseconds
```

This is thanks to yconf, more example units:
https://github.com/processone/yconf/blob/aba6e0bb5d274482caf5447c77d71b50c9418026/test/yconf_test.erl#L618


> Meaning of mod_register: access_from is unclear: Description lets assume this is for controlling registration of new accounts from s2s or existing c2s sessions. But This is not stated.

What do you mean? That's exactly what it says, right?

> access_from: AccessName
> By default, ejabberd doesn’t allow to register new accounts from s2s or existing c2s sessions. You can change it by defining access rule in this option. Use with care: allowing registration from s2s leads to uncontrolled massive accounts creation by rogue users.

How would you rephrase the description?


> mod_stun has an option to enable TLS, but what ciphers, dhfile, and protocoll_options are used?

Oh, no idea. @weiss, any clue?

**Comment by licaon-kter** [comment]
Some info here on TURN TLS: https://github.com/processone/ejabberd/issues/3265

I had to concatenate key+cert to get it recognized.

**Comment by weiss** [comment]
> mod_stun has an option to enable TLS, but what ciphers, dhfile, and protocoll_options are used?

I guess you mean `ejabberd_stun` listeners.  There's currently no way to specify TLS options for those, no.  (With modern A/V solutions, TLS is typically used for circumventing firewalls, not for actually securing the traffic.)

**Comment by badlop** [comment]
I've improved documentation for the first question.

I think the other ones are already answered elsewhere, or the poster didn't provide more details about what should be improved.
