### ISSUE TITLE
mod_disco - name can be arbitrary?

### ISSUE THREAD

**Issue by licaon-kter** [processone/docs.ejabberd.im#97]
https://docs.ejabberd.im/archive/20_04/modules/#mod-disco
```
name: Name
Any arbitrary name of the contact.
```
But isn't https://xmpp.org/extensions/xep-0157.html#registrar-formtype hardcoding these?

Ref: https://process-one.net/logs/ejabberd@conference.process-one.net/2020/09/07.html#17:00:01.608245

**Comment by badlop** [comment]
Well, XEP-0157 defines a few ones, but mod_disco is ready to support any arbitrary one.

It was better expressed in the original option documentation:

> server_info: [ { modules: Modules, name: Name, urls: [URL, ...] } ]:   
>        Specify additional information about the server, as describe
>        Contact Addresses for XMPP Services ([`XEP-0157`](http://xmpp.org/extensions/xep-0157.html)). `Modules`
>        can be the keyword ‘all’, in which case the information is reported
>        in all the services; or a list of `ejabberd` modules, in which case
>        the information is only specified for the services provided by those
>        modules. **Any arbitrary `Name` and `URL` can be specified, not only
>        contact addresses.**

I see several paths:
A) Implement strict option check to only allow the names defined in the XEP
B) Keep code and docs as they are
C) Keep code, but clarify documentation to induce to use the names defined in the XEP, something like:

> name: Name
> The field var name that will be defined. See the XEP for some examples.

I prefer path C.

**Comment by licaon-kter** [comment]
C) here too
